/**
 * Đây là phần dữ liệu sản phẩm được mock tạm thời, sau này sẽ được thay thế bằng dữ liệu thực tế từ server thông qua API.
 */

const products = [
  // Bánh Mousse
  {
    id: 1,
    name: "Mousse socola",
    price: 200000,
    oldPrice: 250000,
    image: "../assets/image/1.sp1.png",
    category: "mousse",
    desc: "Mousse socola là một loại bánh ngọt có kết cấu nhẹ nhàng và mịn màng, được làm từ socola tan chảy, kem tươi và trứng. Bánh thường có hương vị đậm đà của socola, kết hợp với độ béo ngậy của kem tươi, tạo nên một trải nghiệm thưởng thức tuyệt vời cho những người yêu thích socola.",
  },
  {
    id: 2,
    name: "Mousse dâu tây",
    price: 280000,
    oldPrice: 300000,
    image: "../assets/image/1.sp2.png",
    category: "mousse",
    desc: "Cốt vani xen kẽ các tầng bánh. Dưới cùng là tầng bánh mousse dâu tây, tiếp theo là tầng mousse sữa chua và trên cùng là lớp thạch gelatin dâu tây. Trang trí bằng dâu tươi Đà Lạt, việt quất và socola trắng.",
  },
  {
    id: 3,
    name: "Mousse dưa lưới",
    price: 200000,
    oldPrice: 250000,
    image: "../assets/image/1.sp3.png",
    category: "mousse",
    desc: "Chiếc bánh là sự kết hợp của cốt bánh vani mềm ẩm cùng 2 lớp mousse sữa chua và lớp mousse mascarpone dưa lưới thanh mát, ở giữa điểm thêm lớp dưa lưới cắt hạt lựu giòn ngọt, trang trí lớp tráng gương dưa lưới, kem tươi và những viên dưa lưới Ichiba xanh mướt, cảm giác tươi mát khi chạm ngay đầu lưỡi",
  },
  {
    id: 4,
    name: "Mousse việt quất",
    price: 350000,
    oldPrice: 400000,
    image: "../assets/image/1.sp4.png",
    category: "mousse",
    desc: "Cốt vani xen kẽ các tầng bánh. Tầng dưới cùng là lớp mousse việt quất, tiếp theo là tầng mousse sữa chua và trên cùng là lớp thạch gelatin việt quất. Trang trí bằng việt quất, dâu tươi Đà Lạt, socola trắng và lá hương thảo.",
  },
  {
    id: 5,
    name: "Mousse xoài",
    price: 200000,
    oldPrice: 250000,
    image: "../assets/image/1.sp5.png",
    category: "mousse",
    desc: "Bánh mousse mang đậm hương vị xoài ngọt mát dễ chịu, kem tươi whipping cream kết hợp cùng sữa chua cốt vani, trang trí thêm xoài trên mặt bánh để thêm đậm vị cùng socola.",
  },
  {
    id: 6,
    name: "Mousse Chanh Leo",
    price: 200000,
    oldPrice: 250000,
    image: "../assets/image/1.sp6.png",
    category: "mousse",
    desc: "Mousse mát lạnh sử dụng chanh leo tươi bỏ hạt và kem tươi whipping cream cùng cốt bánh vani, trang trí socola.",
  },
  // Bánh mì mặn
  {
    id: 7,
    name: "Mochi đậu đỏ",
    price: 100000,
    oldPrice: null,
    image: "../assets/image/2.sp1.jpg",
    category: "bread salty",
    desc: "Mochi đậu đỏ là một loại bánh ngọt có kết cấu nhẹ nhàng và mịn màng, được làm từ đậu đỏ tươi, kem tươi và trứng. Bánh thường có hương vị ngọt ngào của đậu đỏ, kết hợp với độ béo ngậy của kem tươi, tạo nên một trải nghiệm thưởng thức tuyệt vời cho những người yêu thích trái cây.",
  },
  {
    id: 8,
    name: "Bánh su kem",
    price: 25000,
    oldPrice: null,
    image: "../assets/image/3.sp1.jpg",
    category: "bread salty",
    desc: "Bánh su kem là một loại bánh ngọt có kết cấu nhẹ nhàng và mịn màng, được làm từ kem tươi và trứng. Bánh thường có hương vị ngọt ngào của kem, kết hợp với độ béo ngậy của kem tươi, tạo nên một trải nghiệm thưởng thức tuyệt vời cho những người yêu thích bánh ngọt.",
  },
  {
    id: 9,
    name: "Lemon Cupcakes",
    price: 50000,
    oldPrice: null,
    image: "../assets/image/3.sp2.jpg",
    category: "bread salty",
    desc: "Lemon Cupcakes là một loại bánh ngọt có kết cấu nhẹ nhàng và mịn màng, được làm từ柠檬 (lemon) tươi, kem tươi và trứng. Bánh thường có hương vị chua dịu của柠檬, kết hợp với độ béo ngậy của kem tươi, tạo nên một trải nghiệm thưởng thức tuyệt vời cho những người yêu thích bánh ngọt.",
  },
  {
    id: 10,
    name: "Bánh sừng bò",
    price: 45000,
    oldPrice: null,
    image: "../assets/image/2.sp3.jpg",
    category: "bread salty",
    desc: "Bánh sừng bò là một loại bánh mặn có kết cấu mềm mại và hương vị đậm đà, được làm từ thịt bò, rau củ và các loại gia vị. Bánh thường có hương vị thơm ngon của thịt bò, kết hợp với độ giòn của rau củ, tạo nên một trải nghiệm thưởng thức tuyệt vời cho những người yêu thích bánh mặn.",
  },
  {
    id: 11,
    name: "Quiche rau bina",
    price: 200000,
    oldPrice: null,
    image: "../assets/image/2.sp4.jpg",
    category: "bread salty",
    desc: "Quiche rau bina là một loại bánh mặn có kết cấu mềm mại và hương vị đậm đà, được làm từ rau bina, trứng và các loại gia vị. Bánh thường có hương vị thơm ngon của rau bina, kết hợp với độ béo ngậy của kem tươi, tạo nên một trải nghiệm thưởng thức tuyệt vời cho những người yêu thích bánh mặn.",
  },
  {
    id: 12,
    name: "Fruit Tart",
    price: 30000,
    oldPrice: null,
    image: "../assets/image/3.sp3.jpg",
    category: "bread salty",
    desc: "Fruit Tart là một loại bánh ngọt có kết cấu nhẹ nhàng và mịn màng, được làm từ trái cây tươi, kem tươi và trứng. Bánh thường có hương vị ngọt ngào của trái cây, kết hợp với độ béo ngậy của kem tươi, tạo nên một trải nghiệm thưởng thức tuyệt vời cho những người yêu thích bánh ngọt.",
  },
  {
    id: 13,
    name: "Bánh bông lan trứng muối xốt phô mai",
    price: 100000,
    oldPrice: 150000,
    image:"../assets/image/4.39.jpg",
    category: "bread salty",
    desc: "sự kết hợp hoàn hảo giữa cốt bông lan mềm ẩm, xốp nhẹ và lớp phủ ngập tràn topping. Vị bùi béo của trứng muối, phô mai miếng hòa quyện cùng chà bông đậm đà và xốt phô mai tan chảy mượt mà, tạo nên hương vị mặn ngọt đan xen vô cùng cuốn hút, ăn hoài không ngán."
  },
  {
    id: 14,
    name: "Bánh muffin mặn",
    price: 30000,
    oldPrice: null,
    image: "../assets/image/4.40.jpg",
    category: "bread salty",
    desc: "Món bánh sở hữu phần cốt bông lan mềm xốp, có độ ẩm nhẹ và thơm nức mùi bơ sữa. Sự kết hợp độc đáo giữa vị ngọt dịu của cốt bánh cùng lớp nhân mặn từ lạp xưởng, chà bông và trứng muối bùi béo phía trên tạo nên một trải nghiệm vị giác vô cùng hài hòa, đậm đà và kích thích vị giác mà không hề bị ngấy.",
  },
  {
    id: 15,
    name: "Bánh mì gối chà bông xốt hành",
    price: 80000,
    oldPrice: 100000,
    image: "../assets/image/4.46.jpg",
    category: "bread salty",
    desc: "Món bánh nổi bật với thớ bánh mì mềm mịn, dai dai và có độ kéo sợi cực kì sướng tay. Sự kết hợp giữa vị mặn mặn, thơm giòn của chà bông phết dầu hành cùng lớp sốt mayonnaise béo ngậy được nướng xém vàng trên bề mặt tạo nên hương vị đậm đà, thơm nức mũi",
  },
  {
    id: 16,
    name: "Bánh mì bơ tỏi mềm",
    price: 50000,
    oldPrice: null,
    image: "../assets/image/4.47.jpg",
    category: "bread salty",
    desc: "Món bánh mang đến kết cấu vỏ ngoài vàng ươm, hơi giòn nhẹ nhờ lớp bột áo, bên trong lại cực kỳ mềm ẩm, đặc ruột và dai mịn. Độ ngon của bánh đến từ sự hòa quyện hoàn hảo giữa lớp bơ tỏi thơm nức mũi, xốt phô mai béo ngậy, ngọt dịu giấu bên trong thớ bánh và chút lá thơm nhấn nhá trên bề mặt, tạo nên hương vị béo ngậy, đậm đà siêu kích thích vị giác.",
  },
  {
    id: 17,
    name: "Bánh mì xúc xích",
    price: 20000,
    oldPrice: null,
    image: "../assets/image/4.48.jpg",
    category: "bread salty",
    desc: "Món bánh sở hữu phần cốt bánh mì siêu mềm mịn, ẩm xốp và thơm ngậy mùi bơ sữa. Độ ngon khó cưỡng của bánh đến từ sự kết hợp hoàn hảo giữa cây xúc xích giòn dai, đậm đà ở chính giữa, hòa quyện cùng lớp xốt mayonnaise béo ngậy, tương cà chua ngọt và chút hành tây, lá thơm nướng xém cạnh trên bề mặt, mang lại hương vị vừa quen thuộc vừa gây nghiện.",
  },
  {
    id: 18,
    name: "Bánh tart pizza bò bằm phô mai",
    price: 85000,
    oldPrice: 100000,
    image: "../assets/image/4.50.jpg",
    category: "bread salty",
    desc: "Món bánh gây ấn tượng với phần đế tart ngàn lớp (puff pastry) vàng ươm, khi cắn vào cảm nhận rõ độ giòn rụm, xốp mềm và thơm hương bơ đặc trưng. Điểm nhấn tạo nên độ ngon khó cưỡng chính là phần nhân ngập tràn với thịt bò bằm xào đậm đà, ớt chuông tươi ngọt sần sật, hòa quyện hoàn hảo cùng lớp phô mai mozzarella kéo sợi xém vàng, béo ngậy và xốt cà chua chua ngọt mượt mà.",
  },
  {
    id: 19,
    name: "Bánh gối ngàn lớp nhân mặn",
    price: 30000,
    oldPrice: null,
    image: "../assets/image/4.55.jpg",
    category: "bread salty",
    desc: "Món bánh sở hữu phần vỏ pastry ngàn lớp vàng ươm, giòn rụm và thơm nức hương bơ, khi cắn vào sẽ cảm nhận được từng lớp bánh tách nhẹ tan ngay trong miệng. Độ ngon của bánh nhân lên gấp bội nhờ phần nhân siêu chất lượng bên trong: sự kết hợp hoàn hảo giữa miếng xúc xích (hoặc thịt nguội) đậm đà, trứng gà bùi béo, chà bông mặn ngọt và một chút hành ngò thơm nhẹ, tạo nên một bữa sáng hoặc món ăn nhẹ vô cùng dinh dưỡng và đưa miệng.",
  },
  //Bánh kem
  {
    id: 20,
    name: "Bánh kem cuộn dâu tây",
    price: 45000,
    oldPrice: 80000,
    image: "../assets/image/4.5.jpg",
    category: "cake",
    desc: "Cốt bông lan cuộn siêu mềm xốp, ôm trọn lấy lớp kem tươi thanh mát và những lát dâu tây tươi mọng nước. Vị chua ngọt tự nhiên của dâu tây hòa cùng nét béo nhẹ của kem ăn rất dễ chịu.",
  },
  {
    id: 21,
    name: "Bánh sinh nhật Chocolate dâu tây",
    price: 100000,
    oldPrice: null,
    image: "../assets/image/4.7.jpg",
    category: "cake",
    desc: "Cốt bánh chocolate đậm đà được bao phủ bởi lớp kem ganache mượt mà, đắng nhẹ, điểm xuyết những bông kem bắt mắt và những quả dâu tây đỏ mọng, chua ngọt cân bằng hoàn hảo.",
  },
  {
    id: 22,
    name: "Bánh kem khúc cây",
    price: 100000,
    oldPrice: null,
    image: "../assets/image/4.8.jpg",
    category: "cake",
    desc: "Sọc vỏ cây sô-cô-la đắng thơm mô phỏng mộc mạc, nâng đỡ lớp kem mousse trắng muốt như bông tuyết phía trên. Vị béo nhẹ của kem và dâu tây tươi giúp bánh vừa sang trọng vừa cuốn hút.",
  },
  {
    id: 23,
    name: "Bánh kem Red Velvet",
    price: 100000,
    oldPrice: null,
    image: "../assets/image/4.9 (2).jpg",
    category: "cake",
    desc: "Sắc đỏ kiêu kỳ từ các lớp cốt bánh mang thoảng hương cacao ẩm mịn. Bánh được xen kẽ bởi những tầng kem tươi béo ngậy, mượt mà và dâu tây tươi, tạo nên hương vị ngọt ngào đậm đà.",
  },
  {
    id: 24,
    name: "Bánh kem chuối xốt caramel",
    price: 100000,
    oldPrice: null,
    image: "../assets/image/4.9.jpg",
    category: "cake",
    desc: "Hương vị chuối chín ngọt tự nhiên kết hợp cùng lớp kem tươi mềm mịn và xốt caramel chảy ngậy đắng nhẹ bao quanh. Chút vụn bánh giòn tan ở chính giữa mang lại kết cấu thú vị.",
  },
  {
    id: 25,
    name: "Orange Basque",
    price: 100000,
    oldPrice: null,
    image: "../assets/image/4.11.jpg",
    category: "cake",
    desc: "Cốt bánh cheesecake nướng cháy cạnh béo ngậy, dẻo mềm như tan chảy quyện kem tươi thanh mát. Những lát cam tươi cùng vụn vỏ cam mang lại hương thơm tinh tế, giải ngấy hoàn hảo.",
  },
  {
    id: 26,
    name: "Bánh kem sữa tươi ",
    price: 100000,
    oldPrice: null,
    image: "../assets/image/4.13.jpg",
    category: "cake",
    desc: "Lớp kem tươi phủ ngoài trắng mịn, ngọt dịu và thanh nhẹ. Vị béo của kem được cân bằng hoàn hảo nhờ vị chua nhẹ, giòn giòn của hạt lựu đỏ và dâu tây tươi trang trí phía trên.",
  },
  {
    id: 27,
    name: "Bánh kem Lotus Biscoff",
    price: 100000,
    oldPrice: null,
    image: "../assets/image/4.17.jpg",
    category: "cake",
    desc: "Cốt bánh chiffon mềm ẩm xen kẽ lớp kem tươi vị bánh quy bơ Lotus thơm bùi độc đáo. Mặt bánh trang trí bánh quy Biscoff giòn rụm và xốt caramel chảy nhẹ đậm đà rất Tây.",
  },
  {
    id: 28,
    name: "Bánh kem chuối xốt caramel",
    price: 100000,
    oldPrice: null,
    image: "../assets/image/4.9.jpg",
    category: "cake",
    desc: "Hương vị chuối chín ngọt tự nhiên kết hợp cùng lớp kem tươi mềm mịn và xốt caramel chảy ngậy đắng nhẹ bao quanh. Chút vụn bánh giòn tan ở chính giữa mang lại kết cấu thú vị.",
  },
  {
    id: 29,
    name: "Bánh Chiffon Matcha phủ xốt xoài tươi",
    price: 100000,
    oldPrice: null,
    image: "../assets/image/4.27.jpg",
    category: "cake",
    desc: "Cốt bánh chiffon trà xanh siêu mềm xốp quyện cùng xốt kem matcha chảy mịn màng, béo ngậy. Vị chát nhẹ của trà được cân bằng bằng xoài chín ngọt lịm trên đỉnh bánh.",
  },

];
