/**
 * Đây là phần dữ liệu sản phẩm được mock tạm thời, sau này sẽ được thay thế bằng dữ liệu thực tế từ server thông qua API.
 */

const products = [
  // Bánh Mousse
  {
    id: 1,
    name: "Mousse socola",
    price: 250000,
    oldPrice: 300000,
    image: "../assets/image/1.sp1.png",
    category: "mousse",
    desc: "Mousse socola là một loại bánh ngọt có kết cấu nhẹ nhàng và mịn màng, được làm từ socola tan chảy, kem tươi và trứng. Bánh thường có hương vị đậm đà của socola, kết hợp với độ béo ngậy của kem tươi, tạo nên một trải nghiệm thưởng thức tuyệt vời cho những người yêu thích socola.",
  },
  {
    id: 2,
    name: "Mousse dâu tây",
    price: 280000,
    oldPrice: 300000,
    image: "../assets/image/1.sp2.png",
    category: "mousse",
    desc: "Cốt vani xen kẽ các tầng bánh. Dưới cùng là tầng bánh mousse dâu tây, tiếp theo là tầng mousse sữa chua và trên cùng là lớp thạch gelatin dâu tây. Trang trí bằng dâu tươi Đà Lạt, việt quất và socola trắng.",
  },
  {
    id: 3,
    name: "Mousse dưa lưới",
    price: 200000,
    oldPrice: 250000,
    image: "../assets/image/1.sp3.png",
    category: "mousse",
    desc: "Chiếc bánh là sự kết hợp của cốt bánh vani mềm ẩm cùng 2 lớp mousse sữa chua và lớp mousse mascarpone dưa lưới thanh mát, ở giữa điểm thêm lớp dưa lưới cắt hạt lựu giòn ngọt, trang trí lớp tráng gương dưa lưới, kem tươi và những viên dưa lưới Ichiba xanh mướt, cảm giác tươi mát khi chạm ngay đầu lưỡi",
  },
  {
    id: 4,
    name: "Mousse việt quất",
    price: 350000,
    oldPrice: 400000,
    image: "../assets/image/1.sp4.png",
    category: "mousse",
    desc: "Cốt vani xen kẽ các tầng bánh. Tầng dưới cùng là lớp mousse việt quất, tiếp theo là tầng mousse sữa chua và trên cùng là lớp thạch gelatin việt quất. Trang trí bằng việt quất, dâu tươi Đà Lạt, socola trắng và lá hương thảo.",
  },
  {
    id: 5,
    name: "Mousse xoài",
    price: 250000,
    oldPrice: 300000,
    image: "../assets/image/1.sp5.png",
    category: "mousse",
    desc: "Bánh mousse mang đậm hương vị xoài ngọt mát dễ chịu, kem tươi whipping cream kết hợp cùng sữa chua cốt vani, trang trí thêm xoài trên mặt bánh để thêm đậm vị cùng socola.",
  },
  {
    id: 6,
    name: "Mousse Chanh Leo",
    price: 200000,
    oldPrice: 250000,
    image: "../assets/image/1.sp6.png",
    category: "mousse",
    desc: "Mousse mát lạnh sử dụng chanh leo tươi bỏ hạt và kem tươi whipping cream cùng cốt bánh vani, trang trí socola.",
  },
  {
    id: 46,
    name: "Mousse việt quất và cherry",
    price: 400000,
    oldPrice: 450000,
    image: "../assets/image/4.6.jpg",
    category: "mousse",
    desc: "Lớp kem mousse dẻo mịn phủ bột cacao quyến rũ, kết hợp cùng vị chua ngọt mọng nước từ quả việt quất và cherry tươi, mang lại hương vị tươi mát và béo ngậy đan xen hoàn hảo.",
  },
  {
    id: 47,
    name: "Bánh Tart dâu tây phô mai",
    price: 300000,
    oldPrice: 400000,
    image: "../assets/image/4.10.jpg",
    category: "mousse",
    desc: "Lòng đế tart nướng vàng giòn, thơm nức hương bơ ôm lấy phần kem phô mai chua nhẹ, béo ngậy. Bề mặt xếp đầy dâu tây tươi căng mọng, tạo nên vị chua ngọt bùng nổ rất sảng khoái.",
  },
  {
    id: 48,
    name: "Bánh Tart đào ",
    price: 200000,
    oldPrice: 240000,
    image: "../assets/image/4.12.jpg",
    category: "mousse",
    desc: "Phần đế tart mặn ngọt, giòn rụm nâng đỡ lớp kem phô mai béo ngậy, chua nhẹ phía trên. Mặt bánh phủ đầy những miếng đào tươi sần sật, mọng nước, ăn vô cùng thanh mát.",
  },
  {
    id: 49,
    name: "Bánh kem chuối",
    price: 200000,
    oldPrice: 380000,
    image: "../assets/image/4.19.jpg",
    category: "mousse",
    desc: "Lớp đế bánh biscuit đắng nhẹ ôm trọn phần nhân chuối chín ngọt lịm. Kem tươi béo ngậy được bắt bông tròn đều mướt mắt và phủ đẫm bột cacao, mang đến cảm giác ngọt ngào, mềm tan.",
  },
  {
    id: 50,
    name: "Bánh Tart Banoffee",
    price: 200000,
    oldPrice: 180000,
    image: "../assets/image/4.20.jpg",
    category: "mousse",
    desc: "Phần đế tart giòn rụm chứa đựng lớp nhân xốt sô-cô-la đặc quánh cùng chuối tươi ngọt ngào. Phía trên là lớp kem tươi dày cộp phủ sô-cô-la bào mỏng, ăn cực kỳ thỏa mãn.",
  },
  {
    id: 51,
    name: "Bánh kem Oreo",
    price: 220000,
    oldPrice: null,
    image: "../assets/image/4.21.jpg",
    category: "mousse",
    desc: "Sự đan xen giữa lớp kem sữa chua ngọt dịu và những mẩu bánh vụn Oreo đậm vị cacao. Mặt bánh phủ một lớp bánh quy nghiền xù xì, ẩm mềm và vui miệng khi ăn.",
  },
  {
    id: 52,
    name: " Mini Mousse trà sữa trân châu đường đen",
    price: 95000,
    oldPrice: 130000,
    image: "../assets/image/4.33.jpg",
    category: "mousse",
    desc: "Lớp kem mousse thoảng hương trà thơm nhẹ, ẩm mịn được phủ một lớp kem tươi chảy béo ngậy. Trên cùng là những viên trân châu dẻo dai, ngọt lịm cực kỳ độc đáo.",
  },
    {
    id: 53,
    name: "Mini Cheesecake xoài tươi",
    price: 85000,
    oldPrice: 10000,
    image: "../assets/image/4.37.jpg",
    category: "mousse",
    desc: "Những ổ bánh kem phô mai nhỏ xinh dẻo mịn, béo ngậy đặc trưng, được phủ lớp kem tươi chảy tràn nhẹ nhàng bên hông và nhấn nhá bằng những khối xoài chín ngọt lịm.",
  },
    {
    id: 54,
    name: "Mousse chanh vàng cắt miếng",
    price: 95000,
    oldPrice: null,
    image: "../assets/image/4.52.jpg",
    category: "mousse",
    desc: "Món tráng miệng thanh mát với kết cấu dẻo mềm, nhẹ nhàng hương chanh tự nhiên trên đế bánh mỏng. Bề mặt tráng lớp jelly chanh trong suốt kèm bông kem tươi bắt mắt, mang lại vị chua ngọt sảng khoái.",
  },
    {
    id: 52,
    name: "Tart khoai môn",
    price: 150000,
    oldPrice: null,
    image: "../assets/image/4.35.jpg",
    category: "mousse",
    desc: "Lớp nhân khoai lang tím nghiền mịn được bắt bông xoắn ốc khéo léo trên đế tart bơ giòn rụm, mang lại vị ngọt bùi tự nhiên, thanh nhẹ kết hợp việt quất tươi mộc mạc.",
  },
  
  // Bánh mì mặn
  {
    id: 7,
    name: "Mochi đậu đỏ",
    price: 180000,
    oldPrice: null,
    image: "../assets/image/2.sp1.jpg",
    category: "bread salty",
    desc: "Mochi đậu đỏ là một loại bánh ngọt có kết cấu nhẹ nhàng và mịn màng, được làm từ đậu đỏ tươi, kem tươi và trứng. Bánh thường có hương vị ngọt ngào của đậu đỏ, kết hợp với độ béo ngậy của kem tươi, tạo nên một trải nghiệm thưởng thức tuyệt vời cho những người yêu thích trái cây.",
  },
  {
    id: 8,
    name: "Bánh su kem",
    price: 25000,
    oldPrice: null,
    image: "../assets/image/3.sp1.jpg",
    category: "bread salty",
    desc: "Bánh su kem là một loại bánh ngọt có kết cấu nhẹ nhàng và mịn màng, được làm từ kem tươi và trứng. Bánh thường có hương vị ngọt ngào của kem, kết hợp với độ béo ngậy của kem tươi, tạo nên một trải nghiệm thưởng thức tuyệt vời cho những người yêu thích bánh ngọt.",
  },
  {
    id: 9,
    name: "Lemon Cupcakes",
    price: 80000,
    oldPrice: null,
    image: "../assets/image/3.sp2.jpg",
    category: "bread salty",
    desc: "Lemon Cupcakes là một loại bánh ngọt có kết cấu nhẹ nhàng và mịn màng, được làm từ柠檬 (lemon) tươi, kem tươi và trứng. Bánh thường có hương vị chua dịu của柠檬, kết hợp với độ béo ngậy của kem tươi, tạo nên một trải nghiệm thưởng thức tuyệt vời cho những người yêu thích bánh ngọt.",
  },
  {
    id: 10,
    name: "Bánh sừng bò",
    price: 85000,
    oldPrice: null,
    image: "../assets/image/2.sp3.jpg",
    category: "bread salty",
    desc: "Bánh sừng bò là một loại bánh mặn có kết cấu mềm mại và hương vị đậm đà, được làm từ thịt bò, rau củ và các loại gia vị. Bánh thường có hương vị thơm ngon của thịt bò, kết hợp với độ giòn của rau củ, tạo nên một trải nghiệm thưởng thức tuyệt vời cho những người yêu thích bánh mặn.",
  },
  {
    id: 11,
    name: "Quiche rau bina",
    price: 400000,
    oldPrice: null,
    image: "../assets/image/2.sp4.jpg",
    category: "bread salty",
    desc: "Quiche rau bina là một loại bánh mặn có kết cấu mềm mại và hương vị đậm đà, được làm từ rau bina, trứng và các loại gia vị. Bánh thường có hương vị thơm ngon của rau bina, kết hợp với độ béo ngậy của kem tươi, tạo nên một trải nghiệm thưởng thức tuyệt vời cho những người yêu thích bánh mặn.",
  },
  {
    id: 12,
    name: "Fruit Tart",
    price: 85000,
    oldPrice: null,
    image: "../assets/image/3.sp3.jpg",
    category: "bread salty",
    desc: "Fruit Tart là một loại bánh ngọt có kết cấu nhẹ nhàng và mịn màng, được làm từ trái cây tươi, kem tươi và trứng. Bánh thường có hương vị ngọt ngào của trái cây, kết hợp với độ béo ngậy của kem tươi, tạo nên một trải nghiệm thưởng thức tuyệt vời cho những người yêu thích bánh ngọt.",
  },
  {
    id: 13,
    name: "Bánh bông lan trứng muối xốt phô mai",
    price: 150000,
    oldPrice: 250000,
    image:"../assets/image/4.39.jpg",
    category: "bread salty",
    desc: "sự kết hợp hoàn hảo giữa cốt bông lan mềm ẩm, xốp nhẹ và lớp phủ ngập tràn topping. Vị bùi béo của trứng muối, phô mai miếng hòa quyện cùng chà bông đậm đà và xốt phô mai tan chảy mượt mà, tạo nên hương vị mặn ngọt đan xen vô cùng cuốn hút, ăn hoài không ngán."
  },
  {
    id: 14,
    name: "Bánh muffin mặn",
    price: 30000,
    oldPrice: null,
    image: "../assets/image/4.40.jpg",
    category: "bread salty",
    desc: "Món bánh sở hữu phần cốt bông lan mềm xốp, có độ ẩm nhẹ và thơm nức mùi bơ sữa. Sự kết hợp độc đáo giữa vị ngọt dịu của cốt bánh cùng lớp nhân mặn từ lạp xưởng, chà bông và trứng muối bùi béo phía trên tạo nên một trải nghiệm vị giác vô cùng hài hòa, đậm đà và kích thích vị giác mà không hề bị ngấy.",
  },
  {
    id: 15,
    name: "Bánh mì gối chà bông xốt hành",
    price: 80000,
    oldPrice: 100000,
    image: "../assets/image/4.46.jpg",
    category: "bread salty",
    desc: "Món bánh nổi bật với thớ bánh mì mềm mịn, dai dai và có độ kéo sợi cực kì sướng tay. Sự kết hợp giữa vị mặn mặn, thơm giòn của chà bông phết dầu hành cùng lớp sốt mayonnaise béo ngậy được nướng xém vàng trên bề mặt tạo nên hương vị đậm đà, thơm nức mũi",
  },
  {
    id: 16,
    name: "Bánh mì bơ tỏi mềm",
    price: 50000,
    oldPrice: null,
    image: "../assets/image/4.47.jpg",
    category: "bread salty",
    desc: "Món bánh mang đến kết cấu vỏ ngoài vàng ươm, hơi giòn nhẹ nhờ lớp bột áo, bên trong lại cực kỳ mềm ẩm, đặc ruột và dai mịn. Độ ngon của bánh đến từ sự hòa quyện hoàn hảo giữa lớp bơ tỏi thơm nức mũi, xốt phô mai béo ngậy, ngọt dịu giấu bên trong thớ bánh và chút lá thơm nhấn nhá trên bề mặt, tạo nên hương vị béo ngậy, đậm đà siêu kích thích vị giác.",
  },
  {
    id: 17,
    name: "Bánh mì xúc xích",
    price: 20000,
    oldPrice: null,
    image: "../assets/image/4.48.jpg",
    category: "bread salty",
    desc: "Món bánh sở hữu phần cốt bánh mì siêu mềm mịn, ẩm xốp và thơm ngậy mùi bơ sữa. Độ ngon khó cưỡng của bánh đến từ sự kết hợp hoàn hảo giữa cây xúc xích giòn dai, đậm đà ở chính giữa, hòa quyện cùng lớp xốt mayonnaise béo ngậy, tương cà chua ngọt và chút hành tây, lá thơm nướng xém cạnh trên bề mặt, mang lại hương vị vừa quen thuộc vừa gây nghiện.",
  },
  {
    id: 18,
    name: "Bánh tart pizza bò bằm phô mai",
    price: 85000,
    oldPrice: 100000,
    image: "../assets/image/4.50.jpg",
    category: "bread salty",
    desc: "Món bánh gây ấn tượng với phần đế tart ngàn lớp (puff pastry) vàng ươm, khi cắn vào cảm nhận rõ độ giòn rụm, xốp mềm và thơm hương bơ đặc trưng. Điểm nhấn tạo nên độ ngon khó cưỡng chính là phần nhân ngập tràn với thịt bò bằm xào đậm đà, ớt chuông tươi ngọt sần sật, hòa quyện hoàn hảo cùng lớp phô mai mozzarella kéo sợi xém vàng, béo ngậy và xốt cà chua chua ngọt mượt mà.",
  },
  {
    id: 19,
    name: "Bánh gối ngàn lớp nhân mặn",
    price: 45000,
    oldPrice: null,
    image: "../assets/image/4.55.jpg",
    category: "bread salty",
    desc: "Món bánh sở hữu phần vỏ pastry ngàn lớp vàng ươm, giòn rụm và thơm nức hương bơ, khi cắn vào sẽ cảm nhận được từng lớp bánh tách nhẹ tan ngay trong miệng. Độ ngon của bánh nhân lên gấp bội nhờ phần nhân siêu chất lượng bên trong: sự kết hợp hoàn hảo giữa miếng xúc xích (hoặc thịt nguội) đậm đà, trứng gà bùi béo, chà bông mặn ngọt và một chút hành ngò thơm nhẹ, tạo nên một bữa sáng hoặc món ăn nhẹ vô cùng dinh dưỡng và đưa miệng.",
  },
  //Bánh kem
  {
    id: 20,
    name: "Bánh kem cuộn dâu tây",
    price: 100000,
    oldPrice: 150000,
    image: "../assets/image/4.5.jpg",
    category: "cake",
    desc: "Cốt bông lan cuộn siêu mềm xốp, ôm trọn lấy lớp kem tươi thanh mát và những lát dâu tây tươi mọng nước. Vị chua ngọt tự nhiên của dâu tây hòa cùng nét béo nhẹ của kem ăn rất dễ chịu.",
  },
  {
    id: 21,
    name: "Bánh sinh nhật Chocolate dâu tây",
    price: 400000,
    oldPrice: null,
    image: "../assets/image/4.7.jpg",
    category: "cake",
    desc: "Cốt bánh chocolate đậm đà được bao phủ bởi lớp kem ganache mượt mà, đắng nhẹ, điểm xuyết những bông kem bắt mắt và những quả dâu tây đỏ mọng, chua ngọt cân bằng hoàn hảo.",
  },
  {
    id: 22,
    name: "Bánh kem khúc cây",
    price: 4500000,
    oldPrice: null,
    image: "../assets/image/4.8.jpg",
    category: "cake",
    desc: "Sọc vỏ cây sô-cô-la đắng thơm mô phỏng mộc mạc, nâng đỡ lớp kem mousse trắng muốt như bông tuyết phía trên. Vị béo nhẹ của kem và dâu tây tươi giúp bánh vừa sang trọng vừa cuốn hút.",
  },
  {
    id: 23,
    name: "Bánh kem Red Velvet",
    price: 3800000,
    oldPrice: null,
    image: "../assets/image/4.9 (2).jpg",
    category: "cake",
    desc: "Sắc đỏ kiêu kỳ từ các lớp cốt bánh mang thoảng hương cacao ẩm mịn. Bánh được xen kẽ bởi những tầng kem tươi béo ngậy, mượt mà và dâu tây tươi, tạo nên hương vị ngọt ngào đậm đà.",
  },
  {
    id: 24,
    name: "Bánh kem chuối xốt caramel",
    price: 300000,
    oldPrice: null,
    image: "../assets/image/4.9.jpg",
    category: "cake",
    desc: "Hương vị chuối chín ngọt tự nhiên kết hợp cùng lớp kem tươi mềm mịn và xốt caramel chảy ngậy đắng nhẹ bao quanh. Chút vụn bánh giòn tan ở chính giữa mang lại kết cấu thú vị.",
  },
  {
    id: 25,
    name: "Orange Basque",
    price: 250000,
    oldPrice: null,
    image: "../assets/image/4.11.jpg",
    category: "cake",
    desc: "Cốt bánh cheesecake nướng cháy cạnh béo ngậy, dẻo mềm như tan chảy quyện kem tươi thanh mát. Những lát cam tươi cùng vụn vỏ cam mang lại hương thơm tinh tế, giải ngấy hoàn hảo.",
  },
  {
    id: 26,
    name: "Bánh kem sữa tươi ",
    price: 100000,
    oldPrice: null,
    image: "../assets/image/4.13.jpg",
    category: "cake",
    desc: "Lớp kem tươi phủ ngoài trắng mịn, ngọt dịu và thanh nhẹ. Vị béo của kem được cân bằng hoàn hảo nhờ vị chua nhẹ, giòn giòn của hạt lựu đỏ và dâu tây tươi trang trí phía trên.",
  },
  {
    id: 27,
    name: "Bánh kem Lotus Biscoff",
    price: 200000,
    oldPrice: null,
    image: "../assets/image/4.17.jpg",
    category: "cake",
    desc: "Cốt bánh chiffon mềm ẩm xen kẽ lớp kem tươi vị bánh quy bơ Lotus thơm bùi độc đáo. Mặt bánh trang trí bánh quy Biscoff giòn rụm và xốt caramel chảy nhẹ đậm đà rất Tây.",
  },
  {
    id: 28,
    name: "Bánh kem chuối xốt caramel",
    price: 150000,
    oldPrice: 200000,
    image: "../assets/image/4.9.jpg",
    category: "cake",
    desc: "Hương vị chuối chín ngọt tự nhiên kết hợp cùng lớp kem tươi mềm mịn và xốt caramel chảy ngậy đắng nhẹ bao quanh. Chút vụn bánh giòn tan ở chính giữa mang lại kết cấu thú vị.",
  },
  {
    id: 29,
    name: "Bánh Chiffon Matcha phủ xốt xoài tươi",
    price: 200000,
    oldPrice: null,
    image: "../assets/image/4.27.jpg",
    category: "cake",
    desc: "Cốt bánh chiffon trà xanh siêu mềm xốp quyện cùng xốt kem matcha chảy mịn màng, béo ngậy. Vị chát nhẹ của trà được cân bằng bằng xoài chín ngọt lịm trên đỉnh bánh.",
  },
  //Bánh mì
  {
    id: 30,
    name: "Bánh sừng bò kẹp kem Matcha",
    price: 95000,
    oldPrice: null,
    image: "../assets/image/4.15.jpg",
    category: "bread",
    desc: "Vỏ bánh croissant ngàn lớp xốp giòn, thơm đậm vị bơ nướng kẹp nhân kem tươi trà xanh màu xanh pastel mát mắt, vị chát nhẹ tinh tế hòa cùng việt quất tươi mọng.",
  },
  {
    id: 31,
    name: "Bánh sừng bò kẹp kem tươi nho",
    price: 85000,
    oldPrice: null,
    image: "../assets/image/4.16.jpg",
    category: "bread",
    desc: "Sự kết hợp giữa kết cấu giòn rụm từ vỏ bánh mì sừng bò ngàn lớp và sự mướt mịn, mát lạnh của lớp kem tươi. Những lát nho mẫu đơn xanh mướt mượt, ngọt lịm tăng độ sang xịn mịn.",
  },
  {
    id: 32,
    name: "Bánh mì gối ngàn lớp Matcha",
    price: 85000,
    oldPrice: null,
    image: "../assets/image/4.26.jpg",
    category: "bread",
    desc: "Chiếc bánh mì với tạo hình các đường vân ngàn lớp xếp nếp đều tăm tắp. Cốt bánh mì gối siêu mềm mịn, dai kéo sợi nhẹ hòa quyện hương trà xanh dưa lưới lan tỏa thoang thoảng.",
  },
  {
    id: 33,
    name: "Bánh bông lan chanh vàng",
    price: 60000,
    oldPrice: null,
    image: "../assets/image/4.38.jpg",
    category: "bread",
    desc: "Từng khối bánh vuông vức kết cấu đặc, ẩm mịn và thơm nức hương vỏ chanh tự nhiên. Độ ngon tăng thêm nhờ lớp xốt đường chanh (icing) phủ trên bề mặt mang lại vị chua ngọt sảng khoái.",
  },
  {
    id: 34,
    name: "Bánh mì ngọt kem sữa hạnh nhân",
    price: 50000,
    oldPrice: null,
    image: "../assets/image/4.41.jpg",
    category: "bread",
    desc: "Tạo hình khía cạnh hình bàn tay vàng ươm mộc mạc, thớ bánh bên trong siêu xốp mềm, ẩm mịn chứa nhân kem sữa ngọt dịu và lát hạnh nhân sấy giòn bùi rải trên mặt bánh.",
  },
  {
    id: 35,
    name: "Bánh mì sừng bò truyền thống",
    price: 45000,
    oldPrice: null,
    image: "../assets/image/4.49.jpg",
    category: "bread",
    desc: "Lớp vỏ ngàn lớp nướng chín vàng ruộm, bóng bẩy và giòn rụm. Ruột bánh bên trong xốp nhẹ, có độ đàn hồi và thơm nức hương bơ đặc trưng, ăn rất cuốn.",
  }, 
  //Bánh nướng
  {
    id: 36,
    name: "Bánh quy Lava socola",
    price: 55000,
    oldPrice: null,
    image: "../assets/image/4.22.jpg",
    category: "baked goods",
    desc: "Vỏ bánh quy socola bên ngoài nướng vừa chín tới, xốp mềm và ẩm nhẹ. Phần nhân phô mai sữa chua trắng muốt, dẻo mịn béo ngậy bên trong khi bẻ đôi sẽ tan chảy cực kỳ kích thích.",
  },
    {
    id: 37,
    name: "Bánh Cookies Lava socola",
    price: 55000,
    oldPrice: 40000,
    image: "../assets/image/4.23.jpg",
    category: "baked goods",
    desc: "Viên bánh quy sô-cô-la tròn trịa, xốp mềm vị đắng nhẹ. Tâm bánh ngập tràn nhân cream cheese béo ngậy, nhấn nhá thêm một hạt hạnh nhân sấy giòn rụm ở chính giữa bùi béo đan xen.",
  },
    {
    id: 38,
    name: "Bánh Cookies Lava Matcha",
    price: 55000,
    oldPrice: 45000,
    image: "../assets/image/4.24.jpg",
    category: "baked goods",
    desc: "Vỏ ngoài màu xanh đậm, xốp mềm thơm nức hương matcha. Lòng bánh trũng sâu ôm lấy phần nhân phô mai sữa chua trắng ngần, dẻo ngậy tan chảy và nụ hoa nhài khô tinh tế trên mặt.",
  },
  {
    id: 39,
    name: "Mochi Matcha nhân kem chảy",
    price: 180000,
    oldPrice: 200000,
    image: "../assets/image/4.25.jpg",
    category: "baked goods",
    desc: "Vỏ bánh mì mochi dẻo dai sần sật cực kỳ vui miệng, thoảng hương trà xanh tự nhiên. Khi cắn vào, phần nhân kem matcha đặc quánh, bùng nổ vị ngậy béo, ngọt dịu vô cùng gây nghiện.",
  },
  {
    id: 40,
    name: "Bánh su kem vỏ giòn Matcha",
    price: 95000,
    oldPrice: null,
    image: "../assets/image/4.42.jpg",
    category: "baked goods",
    desc: "Lớp vỏ su kem xù xì, giòn rụm đan xen hạt óc chó bùi bùi. Bên trong ôm trọn lớp nhân kem tươi Matcha dẻo mịn, mang vị ngậy béo hòa cùng chút chát nhẹ đặc trưng của trà xanh.",
  },
  {
    id: 41,
    name: "Bánh su kem vỏ giòn ngập nhân (Set 4 vị)",
    price: 100000,
    oldPrice: null,
    image: "../assets/image/4.43.jpg",
    category: "baked goods",
    desc: "Lớp vỏ nướng xù xì giòn tan ôm trọn các loại nhân kem tươi bắt mắt (matcha chát nhẹ, vani đường bột mướt mịn, kem sữa mè đen thơm bùi hoặc cookies), tạo trải nghiệm bùng nổ vị giác.",
  },
{
    id: 41,
    name: "Bánh socola hạt phỉ cắt miếng",
    price: 150000,
    oldPrice: 200000,
    image: "../assets/image/4.44.jpg",
    category: "baked goods",
    desc: "Sự kết hợp giữa các tầng kem mousse sô-cô-la đắng nhẹ và kem tươi dẻo mịn gối lên nhau. Mặt bánh được phủ một lớp sốt sô-cô-la đông đặc đan xen hạt phỉ giòn rụm, mang lại hương vị quyến rũ.",
  },
{
    id: 42,
    name: "Bánh kem phô mai phủ socola viên",
    price: 100000,
    oldPrice: null,
    image: "../assets/image/4.45.jpg",
    category: "baked goods",
    desc: "Khối bánh cheesecake cắt vuông vắn với phần cốt kem phô mai trắng muốt béo ngậy dẻo mịn trên đế bánh quy đắng. Điểm nhấn là lớp sô-cô-la ganache chảy tràn bao quanh và viên kẹo Ferrero Rocher giòn bùi sang chảnh trên đỉnh.",
  },
{
    id: 43,
    name: "Bánh khoai lang nướng mè đen",
    price: 75000,
    oldPrice: null,
    image: "../assets/image/4.51.jpg",
    category: "baked goods",
    desc: "Các khối khoai lang cắt hạt lựu kết dính khéo léo tạo kết cấu dẻo bùi tự nhiên. Lớp mặt phết lòng đỏ trứng nướng xém cạnh thơm ngậy kết hợp mè đen bùi bùi sần sật rất vui miệng.",
  },
{
    id: 44,
    name: "Bánh sữa tươi nướng phô mai",
    price: 90000,
    oldPrice: 100000,
    image: "../assets/image/4.53.jpg",
    category: "baked goods",
    desc: "Lớp màng bề mặt được nướng cháy xém vàng nâu (Basque style) hơi dai nhẹ, nhưng ẩn sâu bên trong lại là phần cốt sữa chua phô mai mướt mịn, béo ngậy đặc trưng tan chảy trên đầu lưỡi.",
  },
{
    id: 45,
    name: "Bánh gối ngàn lớp cuộn khoai lang phô mai",
    price: 100000,
    oldPrice: null,
    image: "../assets/image/4.54.jpg",
    category: "baked goods",
    desc: "Lớp vỏ pastry ngàn lớp nướng vàng ruộm, giòn tan kèm mè đen bùi thơm. Nhân bên trong quyện giữa khoai lang nghiền ngọt bùi và phô mai tan chảy kéo sợi mặn ngọt cực bắt miệng.",
  },

];
