/**
 * Đây là phần dữ liệu sản phẩm được mock tạm thời, sau này sẽ được thay thế bằng dữ liệu thực tế từ server thông qua API.
 */

const products = [
  // Bánh Mousse
  {
    id: 1,
    name: "Mousse socola",
    price: 200000,
    oldPrice: 250000,
    image: "../assets/image/1.sp1.png",
    category: "mousse",
    desc: "Mousse socola là một loại bánh ngọt có kết cấu nhẹ nhàng và mịn màng, được làm từ socola tan chảy, kem tươi và trứng. Bánh thường có hương vị đậm đà của socola, kết hợp với độ béo ngậy của kem tươi, tạo nên một trải nghiệm thưởng thức tuyệt vời cho những người yêu thích socola.",
  },
  {
    id: 2,
    name: "Mousse dâu tây",
    price: 280000,
    oldPrice: 300000,
    image: "../assets/image/1.sp2.png",
    category: "mousse",
    desc: "Cốt vani xen kẽ các tầng bánh. Dưới cùng là tầng bánh mousse dâu tây, tiếp theo là tầng mousse sữa chua và trên cùng là lớp thạch gelatin dâu tây. Trang trí bằng dâu tươi Đà Lạt, việt quất và socola trắng.",
  },
  {
    id: 3,
    name: "Mousse dưa lưới",
    price: 200000,
    oldPrice: 250000,
    image: "../assets/image/1.sp3.png",
    category: "mousse",
    desc: "Chiếc bánh là sự kết hợp của cốt bánh vani mềm ẩm cùng 2 lớp mousse sữa chua và lớp mousse mascarpone dưa lưới thanh mát, ở giữa điểm thêm lớp dưa lưới cắt hạt lựu giòn ngọt, trang trí lớp tráng gương dưa lưới, kem tươi và những viên dưa lưới Ichiba xanh mướt, cảm giác tươi mát khi chạm ngay đầu lưỡi",
  },
  {
    id: 4,
    name: "Mousse việt quất",
    price: 350000,
    oldPrice: 400000,
    image: "../assets/image/1.sp4.png",
    category: "mousse",
    desc: "Cốt vani xen kẽ các tầng bánh. Tầng dưới cùng là lớp mousse việt quất, tiếp theo là tầng mousse sữa chua và trên cùng là lớp thạch gelatin việt quất. Trang trí bằng việt quất, dâu tươi Đà Lạt, socola trắng và lá hương thảo.",
  },
  {
    id: 5,
    name: "Mousse xoài",
    price: 200000,
    oldPrice: 250000,
    image: "../assets/image/1.sp5.png",
    category: "mousse",
    desc: "Bánh mousse mang đậm hương vị xoài ngọt mát dễ chịu, kem tươi whipping cream kết hợp cùng sữa chua cốt vani, trang trí thêm xoài trên mặt bánh để thêm đậm vị cùng socola.",
  },
  {
    id: 6,
    name: "Mousse Chanh Leo",
    price: 200000,
    oldPrice: 250000,
    image: "../assets/image/1.sp6.png",
    category: "mousse",
    desc: "Mousse mát lạnh sử dụng chanh leo tươi bỏ hạt và kem tươi whipping cream cùng cốt bánh vani, trang trí socola.",
  },
  // Bánh mì mặn
  {
    id: 7,
    name: "Mochi đậu đỏ",
    price: 100000,
    oldPrice: null,
    image: "../assets/image/2.sp1.jpg",
    category: "bread salty",
    desc: "Mochi đậu đỏ là một loại bánh ngọt có kết cấu nhẹ nhàng và mịn màng, được làm từ đậu đỏ tươi, kem tươi và trứng. Bánh thường có hương vị ngọt ngào của đậu đỏ, kết hợp với độ béo ngậy của kem tươi, tạo nên một trải nghiệm thưởng thức tuyệt vời cho những người yêu thích trái cây.",
  },
  {
    id: 8,
    name: "Bánh su kem",
    price: 25000,
    oldPrice: null,
    image: "../assets/image/3.sp1.jpg",
    category: "bread salty",
    desc: "Bánh su kem là một loại bánh ngọt có kết cấu nhẹ nhàng và mịn màng, được làm từ kem tươi và trứng. Bánh thường có hương vị ngọt ngào của kem, kết hợp với độ béo ngậy của kem tươi, tạo nên một trải nghiệm thưởng thức tuyệt vời cho những người yêu thích bánh ngọt.",
  },
  {
    id: 9,
    name: "Lemon Cupcakes",
    price: 50000,
    oldPrice: null,
    image: "../assets/image/3.sp2.jpg",
    category: "bread salty",
    desc: "Lemon Cupcakes là một loại bánh ngọt có kết cấu nhẹ nhàng và mịn màng, được làm từ柠檬 (lemon) tươi, kem tươi và trứng. Bánh thường có hương vị chua dịu của柠檬, kết hợp với độ béo ngậy của kem tươi, tạo nên một trải nghiệm thưởng thức tuyệt vời cho những người yêu thích bánh ngọt.",
  },
  {
    id: 10,
    name: "Bánh sừng bò",
    price: 45000,
    oldPrice: null,
    image: "../assets/image/2.sp3.jpg",
    category: "bread salty",
    desc: "Bánh sừng bò là một loại bánh mặn có kết cấu mềm mại và hương vị đậm đà, được làm từ thịt bò, rau củ và các loại gia vị. Bánh thường có hương vị thơm ngon của thịt bò, kết hợp với độ giòn của rau củ, tạo nên một trải nghiệm thưởng thức tuyệt vời cho những người yêu thích bánh mặn.",
  },
  {
    id: 11,
    name: "Quiche rau bina",
    price: 200000,
    oldPrice: null,
    image: "../assets/image/2.sp4.jpg",
    category: "bread salty",
    desc: "Quiche rau bina là một loại bánh mặn có kết cấu mềm mại và hương vị đậm đà, được làm từ rau bina, trứng và các loại gia vị. Bánh thường có hương vị thơm ngon của rau bina, kết hợp với độ béo ngậy của kem tươi, tạo nên một trải nghiệm thưởng thức tuyệt vời cho những người yêu thích bánh mặn.",
  },
  {
    id: 12,
    name: "Fruit Tart",
    price: 30000,
    oldPrice: null,
    image: "../assets/image/2.sp4.jpg",
    category: "bread salty",
    desc: "Fruit Tart là một loại bánh ngọt có kết cấu nhẹ nhàng và mịn màng, được làm từ trái cây tươi, kem tươi và trứng. Bánh thường có hương vị ngọt ngào của trái cây, kết hợp với độ béo ngậy của kem tươi, tạo nên một trải nghiệm thưởng thức tuyệt vời cho những người yêu thích bánh ngọt.",
  },
];
